force-app/main/default/objects/Live_Approval__c/Live_Approval__c.object-meta.xml
<CustomObject>
    <label>Live Approval</label>
    <nameField>
        <displayFormat>LA-{0000000}</displayFormat>
        <label>Live Approvals Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Live Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_10__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_10__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 10</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals10</relationshipLabel>
    <relationshipName>Live_Approvals10</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_11__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_11__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 11</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals11</relationshipLabel>
    <relationshipName>Live_Approvals11</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_12__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_12__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 12</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals12</relationshipLabel>
    <relationshipName>Live_Approvals12</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_13__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_13__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 13</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals13</relationshipLabel>
    <relationshipName>Live_Approvals13</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_14__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_14__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 14</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals14</relationshipLabel>
    <relationshipName>Live_Approvals14</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_15__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_15__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 15</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals15</relationshipLabel>
    <relationshipName>Live_Approvals15</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_16__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_16__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 16</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals16</relationshipLabel>
    <relationshipName>Live_Approvals16</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_17__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_17__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 17</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals17</relationshipLabel>
    <relationshipName>Live_Approvals17</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_18__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_18__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 18</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals18</relationshipLabel>
    <relationshipName>Live_Approvals18</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_19__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_19__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 19</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals19</relationshipLabel>
    <relationshipName>Live_Approvals19</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_1__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_1__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 1</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals</relationshipLabel>
    <relationshipName>Live_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_20__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_20__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 20</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals20</relationshipLabel>
    <relationshipName>Live_Approvals20</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_2__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_2__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 2</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals2</relationshipLabel>
    <relationshipName>Live_Approvals2</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_3__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_3__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 3</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals3</relationshipLabel>
    <relationshipName>Live_Approvals3</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_4__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_4__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 4</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals4</relationshipLabel>
    <relationshipName>Live_Approvals4</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_5__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_5__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 5</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals5</relationshipLabel>
    <relationshipName>Live_Approvals5</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_6__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_6__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 6</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals6</relationshipLabel>
    <relationshipName>Live_Approvals6</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_7__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_7__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 7</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals7</relationshipLabel>
    <relationshipName>Live_Approvals7</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_8__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_8__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 8</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals8</relationshipLabel>
    <relationshipName>Live_Approvals8</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Approval_Rule_9__c.field-meta.xml
<CustomField>
    <fullName>Approval_Rule_9__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Approval Rule 9</label>
    <referenceTo>RCA_Approval_Rule__c</referenceTo>
    <relationshipLabel>Live Approvals9</relationshipLabel>
    <relationshipName>Live_Approvals9</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>Quote</referenceTo>
    <relationshipLabel>Live Approvals</relationshipLabel>
    <relationshipName>Live_Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Status_1__c.field-meta.xml
<CustomField>
    <fullName>Status_1__c</fullName>
    <label>Status 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Live_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Status_2__c.field-meta.xml
<CustomField>
    <fullName>Status_2__c</fullName>
    <label>Status 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Live_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Status_3__c.field-meta.xml
<CustomField>
    <fullName>Status_3__c</fullName>
    <label>Status 3</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Live_Approval_Status</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_10__c.field-meta.xml
<CustomField>
    <fullName>Triggered_10__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 10</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_11__c.field-meta.xml
<CustomField>
    <fullName>Triggered_11__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 11</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_12__c.field-meta.xml
<CustomField>
    <fullName>Triggered_12__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 12</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_13__c.field-meta.xml
<CustomField>
    <fullName>Triggered_13__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 13</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_14__c.field-meta.xml
<CustomField>
    <fullName>Triggered_14__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 14</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_15__c.field-meta.xml
<CustomField>
    <fullName>Triggered_15__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 15</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_16__c.field-meta.xml
<CustomField>
    <fullName>Triggered_16__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 16</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_17__c.field-meta.xml
<CustomField>
    <fullName>Triggered_17__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 17</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_18__c.field-meta.xml
<CustomField>
    <fullName>Triggered_18__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 18</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_19__c.field-meta.xml
<CustomField>
    <fullName>Triggered_19__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 19</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_1__c.field-meta.xml
<CustomField>
    <fullName>Triggered_1__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 1</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_20__c.field-meta.xml
<CustomField>
    <fullName>Triggered_20__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 20</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_2__c.field-meta.xml
<CustomField>
    <fullName>Triggered_2__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 2</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_3__c.field-meta.xml
<CustomField>
    <fullName>Triggered_3__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 3</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_4__c.field-meta.xml
<CustomField>
    <fullName>Triggered_4__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 4</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_5__c.field-meta.xml
<CustomField>
    <fullName>Triggered_5__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 5</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_6__c.field-meta.xml
<CustomField>
    <fullName>Triggered_6__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 6</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_7__c.field-meta.xml
<CustomField>
    <fullName>Triggered_7__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 7</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_8__c.field-meta.xml
<CustomField>
    <fullName>Triggered_8__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 8</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Live_Approval__c/fields/Triggered_9__c.field-meta.xml
<CustomField>
    <fullName>Triggered_9__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Triggered 9</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/globalValueSets/Live_Approval_Status.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>N/A</fullName>
        <default>true</default>
        <label>N/A</label>
    </customValue>
    <customValue>
        <fullName>Approve</fullName>
    </customValue>
    <customValue>
        <fullName>Reject</fullName>
    </customValue>
    <customValue>
        <fullName>Triggered</fullName>
    </customValue>
    <customValue>
        <fullName>Not Triggered</fullName>
    </customValue>
    <customValue>
        <fullName>Pending</fullName>
    </customValue>
    <customValue>
        <fullName>Error</fullName>
    </customValue>
    <masterLabel>Live Approval Status</masterLabel>
</GlobalValueSet>

force-app/main/default/classes/UpdateLiveApprovalInvocable.cls
/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 09-24-2025
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public with sharing class UpdateLiveApprovalInvocable {

    // Outer wrapper for Flow: contains a list of approval wrappers and a quoteId (string)
    public class Requests {
        @InvocableVariable(label='Approvals' description='List of approval records to apply')
        public List<ApprovalRecordsWrapper> approvals;

        @InvocableVariable(label='Quote Id' description='Quote Id to target')
        public String quoteId;

        public Requests() {}
    }

    

    @InvocableMethod(label='Update Live Approval' description='Update Live_Approval__c fields for given approval rules (groups)')
    public static void updateApprovals(List<Requests> requestGroups) {
        if (requestGroups == null || requestGroups.isEmpty()) return;

        // Build a map of quoteId -> list of approval wrappers
    Map<Id, List<ApprovalRecordsWrapper>> approvalsByQuote = new Map<Id, List<ApprovalRecordsWrapper>>();
    Set<Id> quoteIds = new Set<Id>();
    Set<String> ruleIds = new Set<String>();

        for (Requests rg : requestGroups) {
            if (rg == null) continue;
            Id qId = null;
            if (rg.quoteId != null) {
                try { qId = (Id)rg.quoteId; } catch (Exception e) { qId = null; }
            }
                if (qId == null) continue;

            quoteIds.add(qId);
            if (!approvalsByQuote.containsKey(qId)) approvalsByQuote.put(qId, new List<ApprovalRecordsWrapper>());
            if (rg.approvals != null) {
                approvalsByQuote.get(qId).addAll(rg.approvals);
                for (ApprovalRecordsWrapper ar : rg.approvals) {
                    if (ar != null && ar.approvalRuleId != null) ruleIds.add(ar.approvalRuleId);
                }
            }
        }

        if (quoteIds.isEmpty() || ruleIds.isEmpty()) return;

        // Build WHERE clause to find any Live_Approval__c that references any of these ruleIds
        String whereClause = '';
        List<String> ors = new List<String>();
        for (Integer i = 1; i <= 20; i++) {
            ors.add('Approval_Rule_' + i + '__c IN :ruleIds');
        }

        whereClause = String.join(ors, ' OR ');

    String soql = 'SELECT Id, Quote__c,' +
            ' Approval_Rule_1__c, Approval_Rule_2__c, Approval_Rule_3__c, Approval_Rule_4__c, Approval_Rule_5__c,' +
            ' Approval_Rule_6__c, Approval_Rule_7__c, Approval_Rule_8__c, Approval_Rule_9__c, Approval_Rule_10__c,' +
            ' Approval_Rule_11__c, Approval_Rule_12__c, Approval_Rule_13__c, Approval_Rule_14__c, Approval_Rule_15__c,' +
            ' Approval_Rule_16__c, Approval_Rule_17__c, Approval_Rule_18__c, Approval_Rule_19__c, Approval_Rule_20__c,' +
            ' Triggered_1__c, Triggered_2__c, Triggered_3__c, Triggered_4__c, Triggered_5__c,' +
            ' Triggered_6__c, Triggered_7__c, Triggered_8__c, Triggered_9__c, Triggered_10__c,' +
            ' Triggered_11__c, Triggered_12__c, Triggered_13__c, Triggered_14__c, Triggered_15__c,' +
            ' Triggered_16__c, Triggered_17__c, Triggered_18__c, Triggered_19__c, Triggered_20__c,' +
            ' Status_1__c, Status_2__c, Status_3__c, Status_4__c, Status_5__c,' +
            ' Status_6__c, Status_7__c, Status_8__c, Status_9__c, Status_10__c,' +
            ' Status_11__c, Status_12__c, Status_13__c, Status_14__c, Status_15__c,' +
            ' Status_16__c, Status_17__c, Status_18__c, Status_19__c, Status_20__c,' +
            ' Approver_1__c, Approver_2__c, Approver_3__c, Approver_4__c, Approver_5__c,' +
            ' Approver_6__c, Approver_7__c, Approver_8__c, Approver_9__c, Approver_10__c,' +
            ' Approver_11__c, Approver_12__c, Approver_13__c, Approver_14__c, Approver_15__c,' +
            ' Approver_16__c, Approver_17__c, Approver_18__c, Approver_19__c, Approver_20__c' +
            ' FROM Live_Approval__c WHERE (' + whereClause + ') AND Quote__c IN :quoteIds';

    List<Live_Approval__c> lives = Database.query(soql);

        Map<Id, Live_Approval__c> toUpdateMap = new Map<Id, Live_Approval__c>();

        for (Live_Approval__c la : lives) {
            // Get approvals targeted for this quote
            List<ApprovalRecordsWrapper> approvals = approvalsByQuote.get(la.Quote__c);
            if (approvals == null || approvals.isEmpty()) continue;

            for (ApprovalRecordsWrapper req : approvals) {
                if (req == null || req.approvalRuleId == null) continue;
                Integer foundIndex = null;
                for (Integer i = 1; i <= 20; i++) {
                    String fieldName = 'Approval_Rule_' + i + '__c';
                    Object ruleObj = la.get(fieldName);
                    if (ruleObj != null && String.valueOf(ruleObj) == req.approvalRuleId) {
                        foundIndex = i;
                        break;
                    }
                }
                if (foundIndex != null) {
                    String trigField = 'Triggered_' + foundIndex + '__c';
                    String statusField = 'Status_' + foundIndex + '__c';
                    String approverField = 'Approver_' + foundIndex + '__c';

                    // Convert triggeringStatus string to boolean: accept 'true' (case-insensitive), else false

                    Boolean trigVal = (req.triggeringStatus == true);
                    if(req.triggeringStatus!=null){
                        la.put(trigField, trigVal);
                    }
                    if(req.approvalStatus!=null){
                        la.put(statusField, req.approvalStatus);
                    }

                    if(req.approver!=null){
                        la.put(approverField, req.approver);
                    }

                    toUpdateMap.put(la.Id, la);
                }
            }
        }

        if (!toUpdateMap.isEmpty()) {
            try {
                update toUpdateMap.values();
            } catch (DmlException de) {
                // swallow - Flow can't handle exceptions here; consider logging
            }
        }
    }
}